### ISSUE TITLE
Twitter's bootstrap is redirecting the CSS to a page, breaking the base.html interface

### ISSUE THREAD

**Issue by neverping** [kmike/django-profiling-dashboard#3]
Twitter is redirect its CSS to a page. Because that, the layout is broken.
$ grep stylesheet profiling_dashboard/templates/profiling_dashboard/base.html 
    <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
$ wget -O /dev/null http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css 
--2013-11-27 11:44:09--  http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css
Resolving twitter.github.com... 199.27.78.192, 199.27.72.129
Connecting to twitter.github.com|199.27.78.192|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://twitter.github.io/bootstrap/1.4.0/bootstrap.min.css [following]
--2013-11-27 11:44:10--  http://twitter.github.io/bootstrap/1.4.0/bootstrap.min.css
Resolving twitter.github.io... 199.27.78.133
Connecting to twitter.github.io|199.27.78.133|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://getbootstrap.com/2.3.2/ [following]
--2013-11-27 11:44:10--  http://getbootstrap.com/2.3.2/
Resolving getbootstrap.com... 204.232.175.78
Connecting to getbootstrap.com|204.232.175.78|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11308 (11K) [text/html]
Saving to: ‘/dev/null’

100%[==================================================================================================================>] 11,308      25.9KB/s   in 0.4s   

2013-11-27 11:44:12 (25.9 KB/s) - ‘/dev/null’ saved [11308/11308]

There's a quick solution: Use another link, like this one below. It works pretty well with me.

http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.2/css/bootstrap.min.css

**Comment by kmike** [comment]
Thanks all!
